trigger: none
parameters:
  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - qa
pool: infraprojectpool
stages:
  - stage: initvalidateplan
    displayName: Terraform init validate plan
    jobs:
      - job: initplan
        displayName: Terraform init plan
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            backendServiceArm: 'infraprojectsc'
            backendAzureRmStorageAccountName: 'souravsginfrapro'
            backendAzureRmContainerName: 'souravcontainfrapro'
            backendAzureRmKey: 'dev.terraform.tfstate'

        # - task: TerraformTask@5
        #   displayName: Terraformplan
        #   inputs:
        #     provider: 'azurerm'
        #     command: 'plan'
        #     workingDirectory: '$(System.DefaultWorkingDirectory)/env/${{parameters.env}}'
        #     environmentServiceNameAzureRM: 'infraserviceconnect'
  # - stage: securityscanning
  #   displayName: security scanning
  #   jobs:
  #     - job: scanjob
  #       continueOnError: true
  #       displayName: security scanning
  #       steps:
  #       - task: PowerShell@2
  #         inputs:
  #           targetType: 'inline'
  #           script: 'tflint --chdir=DIR/--recursive'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)'
        
  #       - task: PowerShell@2
  #         inputs:
  #           targetType: 'inline'
  #           script: |
  #             cd $(System.DefaultWorkingDirectory)
  #             infracost configure set api key ico-RDPlxzyPFP1pDz5hCEFFCViMAtq2bK3X

